/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC
 */
public class GiaoDienSuaThongTin extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienSuaThongTin
     */
    public GiaoDienSuaThongTin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ipname = new javax.swing.JTextField();
        ipNS = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ipSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ipEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ipThoat = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        baoloiname = new javax.swing.JLabel();
        baoloiSDT = new javax.swing.JLabel();
        baoloimail = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Sửa Thông Tin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(109, 11, 170, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Họ Và Tên");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 53, 57, 15);

        ipname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipnameMouseClicked(evt);
            }
        });
        getContentPane().add(ipname);
        ipname.setBounds(79, 46, 286, 30);
        getContentPane().add(ipNS);
        ipNS.setBounds(80, 90, 104, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Ngày Sinh");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 100, 52, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("SDT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 100, 22, 15);

        ipSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipSDTMouseClicked(evt);
            }
        });
        getContentPane().add(ipSDT);
        ipSDT.setBounds(220, 90, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 140, 26, 15);

        ipEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ipEmailMouseClicked(evt);
            }
        });
        getContentPane().add(ipEmail);
        ipEmail.setBounds(80, 130, 193, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("@gmail.com");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 140, 64, 15);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tên Đăng Nhập");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 180, 83, 15);

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(jTextField3);
        jTextField3.setBounds(120, 170, 250, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Mật khẩu hiện tại");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 220, 110, 15);

        jLabel9.setText("<HTML><u></u></HTML>");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(216, 410, 0, 0);

        ipThoat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ipThoat.setText("<HTML><u>Thoát</u></HTML>");
        ipThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ipThoatMousePressed(evt);
            }
        });
        getContentPane().add(ipThoat);
        ipThoat.setBounds(180, 360, 34, 15);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Lưu Thông Tin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 330, 109, 23);

        baoloiname.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(baoloiname);
        baoloiname.setBounds(89, 77, 262, 12);

        baoloiSDT.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(baoloiSDT);
        baoloiSDT.setBounds(220, 120, 150, 10);

        baoloimail.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(baoloimail);
        baoloimail.setBounds(90, 160, 180, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Mật khẩu mới");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 260, 90, 15);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(120, 210, 250, 30);
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(120, 250, 250, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Xác thực mật khẩu");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 290, 110, 15);
        getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(120, 290, 250, 30);

        setBounds(0, 0, 421, 422);
    }// </editor-fold>//GEN-END:initComponents

    private void ipThoatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipThoatMousePressed
        new GiaoDienTimVe().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_ipThoatMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(ipname.getText().length() == 0)
           baoloiname.setText("Họ Tên không được để trống");// TODO add your handling code here:
        String str = ipSDT.getText();
       if (str.length() != 10) 
            baoloiSDT.setText("Số điện thoại không hợp lệ");
       for (int i = 0; i < str.length(); i++) {
            if (Character.isLetter(str.charAt(i)))
                 baoloiSDT.setText("Số điện thoại không hợp lệ");
        } 
       if(ipEmail.getText().length() == 0)
            baoloimail.setText("Email không hợp lệ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ipnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipnameMouseClicked
         baoloiname.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ipnameMouseClicked

    private void ipSDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipSDTMouseClicked
         baoloiSDT.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ipSDTMouseClicked

    private void ipEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ipEmailMouseClicked
        baoloimail.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_ipEmailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienSuaThongTin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel baoloiSDT;
    private javax.swing.JLabel baoloimail;
    private javax.swing.JLabel baoloiname;
    private javax.swing.JTextField ipEmail;
    private com.toedter.calendar.JDateChooser ipNS;
    private javax.swing.JTextField ipSDT;
    private javax.swing.JLabel ipThoat;
    private javax.swing.JTextField ipname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
